<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-09-25T15:22:21 IST" name="Suite" finished-at="2021-09-25T15:22:37 IST" duration-ms="15545">
    <groups>
    </groups>
    <test started-at="2021-09-25T15:22:21 IST" name="Test" finished-at="2021-09-25T15:22:37 IST" duration-ms="15545">
      <class name="loginpagetest.TestLoginPage">
        <test-method is-config="true" signature="setup()[pri:0, instance:loginpagetest.TestLoginPage@15c43bd9]" started-at="2021-09-25T15:22:22 IST" name="setup" finished-at="2021-09-25T15:22:25 IST" duration-ms="3274" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="goToLoginPage()[pri:0, instance:loginpagetest.TestLoginPage@15c43bd9]" started-at="2021-09-25T15:22:25 IST" name="goToLoginPage" finished-at="2021-09-25T15:22:30 IST" duration-ms="5088" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToLoginPage -->
        <test-method signature="testLoginWithValidCredential()[pri:1, instance:loginpagetest.TestLoginPage@15c43bd9]" started-at="2021-09-25T15:22:30 IST" name="testLoginWithValidCredential" finished-at="2021-09-25T15:22:33 IST" duration-ms="3347" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at loginpagetest.TestLoginPage.testLoginWithValidCredential(TestLoginPage.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginWithValidCredential -->
        <test-method is-config="true" signature="goToLoginPage()[pri:0, instance:loginpagetest.TestLoginPage@15c43bd9]" started-at="2021-09-25T15:22:33 IST" name="goToLoginPage" finished-at="2021-09-25T15:22:36 IST" duration-ms="2323" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToLoginPage -->
        <test-method signature="testLoginWithInvalidCredential()[pri:2, instance:loginpagetest.TestLoginPage@15c43bd9]" started-at="2021-09-25T15:22:36 IST" name="testLoginWithInvalidCredential" finished-at="2021-09-25T15:22:37 IST" duration-ms="911" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginWithInvalidCredential -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:loginpagetest.TestLoginPage@15c43bd9]" started-at="2021-09-25T15:22:37 IST" name="tearDown" finished-at="2021-09-25T15:22:37 IST" duration-ms="196" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- loginpagetest.TestLoginPage -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
